from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    product_list,
    SearchResultsView,
    about_us,
    return_policy,
    contact,
    career_view,
    vacancy_list,
    print_invoice,
    track_parcel,

)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    # path('category/<slug:slug>/', product_list, name='product_list'),
    path('category/<slug:slug>/', product_list, name='category_detail'),
    # path('category/<slug:slug>/subcategory/<slug:subcategory_slug>/', product_list, name='subcategory_list'),
    path('category/<slug:slug>/subcategory/<slug:subcategory_slug>/', product_list, name='subcategory_detail'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('search/', SearchResultsView.as_view(), name='search'),
    path('about/', about_us, name='about_us'),
    path('return/', return_policy, name='return'),
    path('contact/', contact, name='contact'),
    path('career/',career_view, name='career_view'),
    path('vacancies/',vacancy_list, name='vacancy_list'),
    path('print-invoice/<int:order_id>/', print_invoice, name='print_invoice'),
    path('track/', track_parcel, name='track_parcel'),
]